import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient, type User } from "@supabase/supabase-js";
import { createRoot } from "react-dom/client";
import "./styles.css";

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const supabase = url && key ? createClient(url, key) : null;
type Store = { id: string; name: string; license_status: "active" | "expired"; license_expiry_date: string | null };
type DailyKpi = { sale_day: string; invoices_count: number | string; gross_amount: number | string; discount_amount: number | string; net_amount: number | string };
const amount = (value: number | string) => Number(value || 0);
const date = (value: string | null) => value ? new Date(value).toLocaleDateString("ar-SD") : "—";

function App() {
  const [user, setUser] = useState<User | null>(null), [stores, setStores] = useState<Store[]>([]), [overview, setOverview] = useState<DailyKpi[]>([]), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState(false);
  const developer = user?.app_metadata?.role === "developer";
  const reload = async () => {
    if (!supabase || !developer) return;
    setBusy(true); setError(null);
    const [storeResult, kpiResult] = await Promise.all([
      supabase.from("stores").select("id,name,license_status,license_expiry_date").order("updated_at", { ascending: false }),
      supabase.rpc("developer_sales_overview", { p_from: new Date(Date.now() - 29 * 86_400_000).toISOString() }),
    ]);
    setBusy(false);
    if (storeResult.error) return setError(storeResult.error.message);
    if (kpiResult.error) return setError(kpiResult.error.message);
    setStores(storeResult.data as Store[]); setOverview((kpiResult.data ?? []) as DailyKpi[]);
  };
  useEffect(() => { if (!supabase) return; supabase.auth.getUser().then(({ data }) => setUser(data.user)); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setUser(session?.user ?? null)); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { void reload(); }, [developer]);
  const login = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; setBusy(true); setError(null); const { data, error: loginError } = await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (loginError) return setError("الإيميل أو كلمة السر ما صحيحة."); if (data.user.app_metadata?.role !== "developer") { await supabase.auth.signOut(); setError("الحساب ده ما حساب مطور."); } };
  const cancel = async (store: Store) => { if (!supabase || !confirm(`تلغي اشتراك ${store.name}؟ بيتقفل لمن جهاز التاجر يتصل بالنت.`)) return; setBusy(true); const { error: callError } = await supabase.functions.invoke("admin-license", { body: { action: "cancel", storeId: store.id } }); setBusy(false); if (callError) setError(callError.message); else void reload(); };
  if (!supabase) return <SetupError/>;
  if (!user) return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} submit={login} error={error} busy={busy}/>;
  if (!developer) return <main dir="rtl" className="grid min-h-screen place-items-center p-6"><p>ما عندك صلاحية مطور.</p></main>;
  return <main dir="rtl" className="mx-auto min-h-screen max-w-7xl p-6 md:p-10"><header className="mb-8 flex items-center justify-between"><div><p className="text-sm font-semibold text-indigo-400">نقطة بيع بدون نت</p><h1 className="text-3xl font-bold">لوحة المطور</h1></div><button onClick={() => void supabase.auth.signOut()} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">تسجيل خروج</button></header>{error && <p className="mb-5 rounded-lg bg-rose-950 p-3 text-rose-200">{error}</p>}<OverviewDashboard rows={overview} reload={reload} busy={busy}/><ProvisionMerchant onComplete={reload}/><section className="mt-6 rounded-2xl bg-slate-900 p-6 shadow-xl"><Title title="متاجر العملاء" reload={reload} busy={busy}/><div className="mt-4 overflow-x-auto"><table className="w-full text-right text-sm"><thead className="border-b border-slate-700 text-slate-400"><tr><th className="pb-3">المتجر</th><th>الحالة</th><th>الانتهاء</th><th>إجراء</th></tr></thead><tbody>{stores.map((store) => <tr key={store.id} className="border-b border-slate-800"><td className="py-4"><p>{store.name}</p><p dir="ltr" className="font-mono text-xs text-slate-500">{store.id}</p></td><td><Status value={store.license_status}/></td><td>{date(store.license_expiry_date)}</td><td>{store.license_status === "active" && <button onClick={() => void cancel(store)} disabled={busy} className="rounded bg-rose-950 px-3 py-2 text-xs text-rose-200">ألغِ الرخصة</button>}</td></tr>)}{!stores.length && <Empty colSpan={4} text="ما في متاجر لسه."/>}</tbody></table></div></section></main>;
}

function OverviewDashboard({ rows, reload, busy }: { rows: DailyKpi[]; reload(): Promise<void>; busy: boolean }) {
  const total = useMemo(() => rows.reduce((sum, row) => ({ invoices: sum.invoices + amount(row.invoices_count), gross: sum.gross + amount(row.gross_amount), discount: sum.discount + amount(row.discount_amount), net: sum.net + amount(row.net_amount) }), { invoices: 0, gross: 0, discount: 0, net: 0 }), [rows]);
  const chartRows = rows.slice(-14), max = Math.max(1, ...chartRows.map((row) => amount(row.net_amount)));
  return <section className="mb-6 rounded-2xl bg-slate-900 p-6 shadow-xl"><Title title="لمحة المبيعات — آخر 30 يوم" reload={reload} busy={busy}/><p className="mt-2 text-sm text-slate-400">إجماليات فقط؛ ما في فواتير أو أصناف أو بيانات زبائن ظاهرة هنا.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="عدد الفواتير" value={total.invoices.toLocaleString("ar-SD")}/><Metric label="إجمالي قبل الخصم" value={total.gross.toFixed(2)}/><Metric label="إجمالي الخصومات" value={total.discount.toFixed(2)}/><Metric label="صافي المبيعات" value={total.net.toFixed(2)} tone="emerald"/></div><div className="mt-6"><h3 className="font-medium">صافي المبيعات يوم بيوم — آخر 14 يوم</h3><div className="mt-4 flex h-48 items-end gap-2 border-b border-slate-700 pb-6">{chartRows.map((row) => <div key={row.sale_day} className="group flex h-full min-w-0 flex-1 flex-col justify-end"><div title={`${row.sale_day}: ${amount(row.net_amount).toFixed(2)}`} style={{ height: `${Math.max(3, amount(row.net_amount) / max * 100)}%` }} className="rounded-t bg-indigo-500 transition group-hover:bg-indigo-300"/><span className="mt-2 truncate text-center text-[10px] text-slate-400">{new Date(`${row.sale_day}T00:00:00Z`).toLocaleDateString("ar-SD", { day: "numeric", month: "numeric" })}</span></div>)}{!chartRows.length && <p className="m-auto text-sm text-slate-500">ما في مبيعات متزامنة خلال الفترة دي.</p>}</div></div></section>;
}

function ProvisionMerchant({ onComplete }: { onComplete(): Promise<void> }) {
  const [storeName, setStoreName] = useState(""), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [deviceId, setDeviceId] = useState(""), [expiry, setExpiry] = useState(oneYear), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [ready, setReady] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; setBusy(true); setError(null); const { data, error: callError } = await supabase.functions.invoke("admin-license", { body: { action: "provision", storeName, merchantEmail: email, merchantPassword: password, deviceId, expiresAt: new Date(`${expiry}T23:59:59.999Z`).toISOString() } }); setBusy(false); if (callError) return setError(callError.message); if (!data?.clientSetup) return setError("السيرفر ما رجع ملف الإعداد."); downloadSetup(data.clientSetup, storeName); setPassword(""); setReady(true); await onComplete(); };
  return <section className="rounded-2xl bg-slate-900 p-6 shadow-xl"><h2 className="text-xl font-semibold">أضف تاجر جديد كامل</h2><p className="mt-2 text-sm text-slate-400">ينشئ حساب التاجر، المتجر، رخصة مرتبطة بالجهاز، وينزّل ملف الإعداد. ما بنحفظ كلمة السر أو التوكن في الملف.</p><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={submit}><Field label="اسم المتجر"><input value={storeName} onChange={(event) => setStoreName(event.target.value)} required className="input"/></Field><Field label="إيميل التاجر"><input dir="ltr" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required className="input"/></Field><Field label="كلمة سر أولية (12 حرف على الأقل)"><input dir="ltr" type="password" minLength={12} value={password} onChange={(event) => setPassword(event.target.value)} required className="input"/></Field><Field label="رقم جهاز التاجر"><input dir="ltr" value={deviceId} onChange={(event) => setDeviceId(event.target.value)} required className="input" placeholder="ينسخ من شاشة ربط المتجر"/></Field><Field label="تاريخ الانتهاء"><input type="date" value={expiry} onChange={(event) => setExpiry(event.target.value)} min={new Date().toISOString().slice(0, 10)} required className="input"/></Field><div className="flex items-end"><button disabled={busy} className="w-full rounded-lg bg-indigo-600 p-3 font-semibold disabled:opacity-50">{busy ? "جاري الإنشاء…" : "أنشئ ونزّل ملف التاجر"}</button></div></form>{error && <p className="mt-4 rounded bg-rose-950 p-3 text-sm text-rose-200">{error}</p>}{ready && <p className="mt-4 rounded bg-emerald-950 p-3 text-sm text-emerald-200">تم. أرسل ملف الإعداد للتاجر مع برنامج Electron، وهو يختارو من شاشة «ربط المتجر أول مرة».</p>}</section>;
}
function Title({ title, reload, busy }: { title: string; reload(): Promise<void>; busy: boolean }) { return <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={() => void reload()} disabled={busy} className="rounded-lg bg-slate-800 px-3 py-2 text-sm disabled:opacity-50">حدّث</button></div>; }
function Metric({ label, value, tone = "slate" }: { label: string; value: string; tone?: "slate" | "emerald" }) { return <div className={`rounded-xl p-4 ${tone === "emerald" ? "bg-emerald-950/50" : "bg-slate-800"}`}><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>; }
function Empty({ colSpan, text }: { colSpan: number; text: string }) { return <tr><td colSpan={colSpan} className="py-8 text-center text-slate-500">{text}</td></tr>; }
function downloadSetup(setup: unknown, name: string) { const blob = new Blob([JSON.stringify(setup, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `pos-setup-${name.replace(/[^a-z0-9_-]/gi, "-") || "merchant"}.json`; link.click(); URL.revokeObjectURL(link.href); }
function Field(props: { label: string; children: React.ReactNode }) { return <label className="block text-sm text-slate-300"><span className="mb-2 block">{props.label}</span>{props.children}</label>; }
function Status({ value }: { value: Store["license_status"] }) { return <span className={value === "active" ? "text-emerald-300" : "text-rose-300"}>{value === "active" ? "شغالة" : "منتهية"}</span>; }
function Login(props: { email: string; password: string; setEmail(value: string): void; setPassword(value: string): void; submit(event: FormEvent): void; error: string | null; busy: boolean }) { return <main dir="rtl" className="grid min-h-screen place-items-center p-6"><form onSubmit={props.submit} className="w-full max-w-md rounded-2xl bg-slate-900 p-8"><h1 className="text-3xl font-bold">لوحة المطور</h1>{props.error && <p className="mt-4 text-rose-300">{props.error}</p>}<Field label="الإيميل"><input dir="ltr" type="email" value={props.email} onChange={(event) => props.setEmail(event.target.value)} required className="input"/></Field><Field label="كلمة السر"><input dir="ltr" type="password" value={props.password} onChange={(event) => props.setPassword(event.target.value)} required className="input"/></Field><button disabled={props.busy} className="mt-6 w-full rounded-lg bg-indigo-600 p-3">ادخل</button></form></main>; }
function SetupError() { return <main dir="rtl" className="grid min-h-screen place-items-center p-6 text-center"><p>إعدادات لوحة المطور ناقصة. أضف VITE_SUPABASE_URL وVITE_SUPABASE_PUBLISHABLE_KEY في apps/admin/.env.local.</p></main>; }
function oneYear() { const day = new Date(); day.setFullYear(day.getFullYear() + 1); return day.toISOString().slice(0, 10); }
createRoot(document.getElementById("root")!).render(<App/>);
